version: '2'
services:
  server:
    build:
      context: documentation-theme-jekyll-gh-pages
      dockerfile: Dockerfile
    image: result/latest
    ports:
      - "4000:4000"
    volumes:
      - ".:/src"